### ISSUE TITLE
eigenMT output - one SNP per feature

### ISSUE THREAD

**Issue by gouthamatla** [joed3/eigenMT#2]
Hi All,

I have a very trivial question as I am not from genetics background.  I read that the eigenMT outputs only one lead SNP per feature ( gene ). As its possible that a gene might be associated with multiple SNPs, I am wondering why eigenMT reports only one SNP per gene. Is there a way to report all significantly associated SNPs per gene ?

Thanks,
Goutham A

**Comment by joed3** [comment]
Hey Goutham A, 

No worries, it's not a trivial question. The goal of eigenMT is to provided calibrated p-values from an eQTL study at the level of the gene. In other words, we are only trying to make a statement regarding whether or not a gene has a significantly associated SNP. We do not attempt to report all possible significantly associated SNPs for a gene due to power constraints. Current eQTL studies have relatively small sample sizes compared to larger QTL or GWAS studies, and the number of potential tests to correct for is extremely large. For these reasons, we only report the most strongly associated SNP for each gene. I hope this helps; let me know if you have more questions. Apologies for the long delay, I've moved on to a different position and do not check this git repo often. 

Best,

Joe

**Comment by gouthamatla** [comment]
Thank you very much for the explanation.
